### ISSUE TITLE
Access-Control-Allow-Origin Support please

### ISSUE THREAD

**Issue by ludagoo** [loansindi/ps1rfid#14]

**Comment by loansindi** [comment]
can you give me more details on what this means?

**Comment by ludagoo** [comment]
Essentially a legit HTTP header including Access-Control-Allow-Origin so that we can do fun stuff in JS from the member site
I think it is done with ` w.Header().Set("Access-Control-Allow-Origin", "*")`
I think changing main.go like so:

``` go
	go http.HandleFunc("/open", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Write([]byte("Okay"))
		openDoor(*splate, publisher)
```

If that works we could change "*" to specifically the member site

**Comment by loansindi** [comment]
If you find me in the space some day that's not a tuesday evening, I can show you how I'm doing deployment on these (while implementing this change), if you'd like.

**Comment by ludagoo** [comment]
ok
