### ISSUE TITLE
Front door does unlock

### ISSUE THREAD

**Issue by chow11** [loansindi/ps1rfid#19]
Scanning an RFID (one that was a few minutes prior registered using the back door), does not show the code at http://frontdoor.pumpingstationone.org:8080/  (Return just says Code: )

It appears to read the RFID tag, I hear a beep and the LED in the window lights, but I do not hear anything (I was expecting a door unlock relay or something).

**Comment by chow11** [comment]
Update:  Door DOES unlock (stupid user error) however the RFID code does not display for me with the above URL.

**Comment by loansindi** [comment]
The code will only show up for an unregistered tag.

If the lights turn on, the door's unlocking (unless some wiring has come
loose, the LEDs are in parallel with the strike plate). The click isn't
very loud on the front door - you may need to pull the door towards the
outside a little bit to get the strike plate free.

**Comment by chow11** [comment]
ah thx that explains the web issue.  I'll update the wiki when I get home

Sent from my iPhone

On Aug 11, 2015, at 9:30 PM, Derek Bever <notifications@github.com<mailto:notifications@github.com>> wrote:

The code will only show up for an unregistered tag.

If the lights turn on, the door's unlocking (unless some wiring has come
loose, the LEDs are in parallel with the strike plate). The click isn't
very loud on the front door - you may need to pull the door towards the
outside a little bit to get the strike plate free.

**Comment by loansindi** [comment]
Working as expected. Thanks for opening an issue though!
